### PR TITLE
Fix compilation error on Windows

### PR DESCRIPTION
**Pull request by tomaka**
Introduced in #87

Better continuous integration would be great. It's the second time in three days that one of the official crates doesn't compile on Windows.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Do you know if it's possible to enable continuous integration for windows? We'd love to support it, we just don't know where to find it other than hosting it ourselves :(

**Comment by alexcrichton** [comment]
Thanks though!

**Comment by tomaka** [comment]
I'm using [appveyor](http://www.appveyor.com/).
See for example [what I do for glutin](https://github.com/tomaka/glutin/blob/master/appveyor.yml).

**Comment by tomaka** [comment]
It works great, the only problem is that there's a ~10-15mn wait in the queue.
